name: /home/lotfi/Projects/MapTravelling/map
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - anaconda-anon-usage=0.7.5=pyhb46e38b_100
  - anaconda-auth=0.12.3=py313h06a4308_0
  - anaconda-cli-base=0.7.0=py313h06a4308_0
  - anaconda-client=1.14.0=py313h06a4308_0
  - anaconda-navigator=2.7.0=py313h06a4308_1
  - annotated-types=0.6.0=py313h06a4308_1
  - aom=3.9.1=hac33072_0
  - archspec=0.2.5=pyhd3eb1b0_0
  - attr=2.5.2=h47b2149_0
  - attrs=25.4.0=py313h06a4308_2
  - blas=1.0=mkl
  - boltons=25.0.0=py313h06a4308_0
  - brotlicffi=1.2.0.0=py313h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hd44998d_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.01.04=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - chardet=5.2.0=py313h06a4308_0
  - charset-normalizer=3.4.4=py313h06a4308_0
  - click=8.2.1=py313h06a4308_1
  - conda=25.11.1=py313h06a4308_0
  - conda-libmamba-solver=25.11.0=pyhdf14ebd_0
  - conda-package-handling=2.4.0=py313h06a4308_1
  - conda-package-streaming=0.12.0=py313h06a4308_1
  - conda-repo-cli=1.0.173=py313h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=46.0.3=py313h0a354b3_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py313h06a4308_0
  - double-conversion=3.3.1=h6a678d5_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=8.0.1=gpl_h95b8bfc_907
  - fmt=11.2.0=hca5f364_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freeglut=3.8.0=h02bc977_0
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - frozendict=2.4.6=py313hee96239_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glslang=15.3.0=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gtest=1.17.0=h5f83a47_0
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - icu=75.1=he02047a_0
  - idna=3.11=py313h06a4308_0
  - imath=3.2.2=hde8ca8f_0
  - intel-gmmlib=22.9.0=h24d9097_0
  - intel-media-driver=26.1.0=h7354ed3_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jansson=2.14=h5eee18b_1
  - jaraco.classes=3.4.0=py313h06a4308_0
  - jaraco.context=6.1.0=py313h06a4308_0
  - jaraco.functools=4.4.0=py313h06a4308_0
  - jasper=4.2.8=he3c4edf_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - joblib=1.5.3=py313h06a4308_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h06a4308_0
  - jsonschema=4.25.1=py313h06a4308_0
  - jsonschema-specifications=2025.9.1=py313h06a4308_0
  - jupyter_core=5.9.1=py313h06a4308_0
  - keyring=25.7.0=py313h06a4308_0
  - krb5=1.21.3=h723845a_4
  - lame=3.100=hbd0596d_1
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.27.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.5=h088129d_0
  - libarchive=3.8.5=gpl_hc2c16d8_100
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif=1.3.0=h6395336_2
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libcap=2.77=h47b2149_0
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libclang-cpp21.1=21.1.8=default_h05d3d09_0
  - libclang13=21.1.8=default_hb7eddd9_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.5.0=hb705b29_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglu=9.0.3=h60c0c69_1
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hf80d704_0
  - libjpeg-turbo=3.1.3=h47b2149_0
  - libjxl=0.11.1=ha09017c_8
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=13_h8876d29_netlib
  - liblapacke=3.9.0=13_hb041515_netlib
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libmamba=2.3.2=h860b5fb_1
  - libmambapy=2.3.2=py313h3f77f5b_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.12.0=qt6_py313h7c914ad_611
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopenvino=2025.3.0=hb617929_0
  - libopenvino-auto-batch-plugin=2025.3.0=hed573e4_0
  - libopenvino-auto-plugin=2025.3.0=hed573e4_0
  - libopenvino-hetero-plugin=2025.3.0=hd41364c_0
  - libopenvino-intel-cpu-plugin=2025.3.0=hb617929_0
  - libopenvino-intel-gpu-plugin=2025.3.0=hb617929_0
  - libopenvino-intel-npu-plugin=2025.3.0=hb617929_0
  - libopenvino-ir-frontend=2025.3.0=hd41364c_0
  - libopenvino-onnx-frontend=2025.3.0=h1862bb8_0
  - libopenvino-paddle-frontend=2025.3.0=h1862bb8_0
  - libopenvino-pytorch-frontend=2025.3.0=hecca717_0
  - libopenvino-tensorflow-frontend=2025.3.0=h0767aad_0
  - libopenvino-tensorflow-lite-frontend=2025.3.0=hecca717_0
  - libopus=1.6.1=h9f10d21_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.54=hee55ce4_0
  - libpq=18.1=h5c52fec_2
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=heac8642_0
  - libsolv=0.7.30=h6f1ccf3_2
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.3=h6569c3e_0
  - libunistring=1.3=hb25bd0a_0
  - libunwind=1.8.3=h9c1abfd_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.3=h5347b49_0
  - libva=2.23.0=h80f46ad_0
  - libvorbis=1.3.7=h536e056_1
  - libvpl=2.15.0=h7354ed3_0
  - libvpx=1.15.2=h4cb591d_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxkbfile=1.1.0=hf54ef8a_2
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h7b6447c_2
  - markdown-it-py=4.0.0=py313h06a4308_1
  - mdurl=0.1.2=py313h06a4308_0
  - menuinst=2.4.2=py313h06a4308_1
  - mesalib=25.0.5=h57bcd07_2
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - more-itertools=10.8.0=py313h06a4308_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.1=py313h6a678d5_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - navigator-updater=0.6.0=py313h06a4308_0
  - nbformat=5.10.4=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numpy=2.3.1=py313h8d96ed3_0
  - numpy-base=2.3.1=py313h8e760e0_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - opencv=4.12.0=qt6_py313h6537eeb_611
  - openexr=3.4.4=h40f6f1d_1
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openjph=0.26.0=h8d634f6_0
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py313h06a4308_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=hf426167_0
  - pillow=12.1.0=py313h80991f8_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pkce=1.0.3=py313h06a4308_0
  - platformdirs=4.5.0=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - psutil=7.0.0=py313hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - py-opencv=4.12.0=qt6_py313hc0a75a6_611
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.23=py313h06a4308_0
  - pydantic=2.12.4=py313h06a4308_0
  - pydantic-core=2.41.5=py313h498d7c9_1
  - pydantic-settings=2.12.0=py313h06a4308_0
  - pygments=2.19.2=py313h06a4308_0
  - pyjwt=2.10.1=py313h06a4308_1
  - pyside6=6.10.1=py313h85046ba_0
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.2=hf636f53_101_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-dotenv=1.2.1=py313h06a4308_0
  - python-fastjsonschema=2.21.2=py313h06a4308_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.3=py313h591646f_0
  - qt6-main=6.10.1=hca0d9c9_0
  - qtpy=2.4.3=py313h06a4308_0
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.11.05=h5301d42_0
  - readchar=4.2.1=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py313h06a4308_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=py313h06a4308_1
  - requests-toolbelt=1.0.0=py313h06a4308_0
  - rich=14.2.0=py313h06a4308_0
  - rpds-py=0.28.0=py313h498d7c9_0
  - ruamel.yaml=0.18.16=py313h4aee224_0
  - ruamel.yaml.clib=0.2.14=py313h4aee224_0
  - scikit-learn=1.8.0=py313h86c3e14_0
  - scipy=1.16.0=py313h0cc6016_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.22=h68140b3_0
  - secretstorage=3.4.0=py313h3e8c6aa_0
  - semver=3.0.4=py313h06a4308_0
  - setuptools=72.1.0=py313h06a4308_0
  - shaderc=2025.5=hfeb5959_0
  - shellingham=1.5.4=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.1=he0a8d7e_0
  - svt-av1=3.1.2=h7354ed3_0
  - tabulate=0.9.0=py313h06a4308_0
  - tbb=2021.13.0=hb700be7_5
  - tbb-devel=2021.13.0=h51de99f_5
  - threadpoolctl=3.5.0=py313h7040dfc_1
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.4.0=py313h06a4308_0
  - tqdm=4.67.1=py313h7040dfc_1
  - traitlets=5.14.3=py313h06a4308_0
  - truststore=0.10.1=py313h06a4308_1
  - typer=0.20.0=py313h06a4308_0
  - typer-slim=0.20.0=py313h06a4308_0
  - typer-slim-standard=0.20.0=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing-inspection=0.4.2=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzdata=2025c=he532380_0
  - ujson=5.11.0=py313hbdd6827_0
  - urllib3=2.6.3=py313h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wayland-protocols=1.47=h51f6af0_0
  - wheel=0.46.3=py313h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxscrnsaver=1.2.4=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.3.2=hceb46e0_1
  - zstandard=0.24.0=py313h3d778a8_0
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/lotfi/Projects/MapTravelling/map
